title: The Icaro programming language
description: JVM ecosystem made simple
buttons:
  github_url: https://github.com/LGala/Icaro
  github_title: Icaro repo
  zip_hide: true
  tar_hide: true
theme: jekyll-theme-cayman
