title: The Icaro programming language
description: JVM ecosystem made simple
theme: jekyll-theme-cayman
darkmode: true
buttons:
      zip_url: http://example.com/
      zip_title: Title
      zip_hide: true
      tar_url: http://example.com/
      tar_title: Title
      tar_hide: true
      github_hide: true # hides "View on Github"
